# Generated by Django 2.2 on 2019-04-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('from_field', models.DateField(db_column='from')),
                ('to', models.DateField()),
            ],
            options={
                'db_table': 'experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lehmanuser',
            fields=[
                ('emplid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lehmanuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lehmanlinkapp.Lehmanuser')),
                ('grad_date', models.DateField()),
            ],
            options={
                'db_table': 'alumni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coursesection',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lehmanlinkapp.Lehmanuser')),
                ('cs_year', models.TextField()),
                ('semester', models.CharField(max_length=6)),
                ('vis', models.IntegerField()),
            ],
            options={
                'db_table': 'coursesection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lehmanlinkapp.Lehmanuser')),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='lehmanlinkapp.Lehmanuser')),
                ('major_vis', models.IntegerField()),
                ('minor_vis', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
